/**
 * Created by acouette on 05/06/16.
 */

translations['en']['home'] = {
    "carousel1Item1": "a trad : Logiciel de gestion logistique en ligne pour PME",
    "carousel2Item1": "a trad : Une solution adaptée aux besoins de PME industrielles, distributeurs et prestataires logistiques",
    "carousel2Item2": "a trad : Complète, elle dispose des fonctionnalités des leaders du marché, à un coût adapté",
    "carousel3Item1": "a trad : Simple et rapide à mettre en œuvre et à utiliser, aucune infrastructure informatique n’est à installer",
    "carousel3Item2": "a trad : Economique, le budget en coûts variables est lié au nombre de transactions",
    "carousel3Item3": "a trad : Connectée aux systèmes d’information des partenaires de vos supply chain",
    "marketingSeeDetails": "View details",
    "marketingServicesHeading": "Services",
    "marketingServicesContent": "a trad : Mise en œuvre simple, fiable, économique et rapide de votre WMS",
    "marketingSolutionsHeading": "Solutions",
    "marketingSolutionsContent": "a trad : Supporte l’ensemble des processus des plates-formes logistiques",
    "marketingSupportHeading": "Support",
    "marketingSupportContent": "a trad : bien utiliser votre solution sur site",
    "featurette1Heading1": "a trad : Une solution logicielle",
    "featurette1Heading2": "a trad :  de gestion logistique en ligne",
    "featurette1Content1": "a trad : Adaptée aux besoins de PME industrielles, distributeurs et prestataires logistiques",
    "featurette1Content2": "a trad : Pour la gestion des magasins des sites de production, des plates formes de distribution, des entrepôts de stockage et des sites de préparation de commandes",
    "featurette1Content3": "a trad : Simple et rapide à mettre en œuvre et à utiliser, aucune infrastructure informatique n’est à installer",
    "featurette1Content4": "a trad : Complète, elle dispose des fonctionnalités des leaders du marché, à un coût adapté aux PME",
    "featurette1Content5": "a trad : Economique, le budget en coûts variables est lié au nombre de transactions, sans obligation d’abonnement ni d’engagement de durée",
    "featurette1Content6": "a trad : Fiable, sécurisée et toujours disponible pour les utilisateurs, dans le monde",
    "featurette1Content7": "a trad : Connectée aux systèmes d’information des partenaires de vos supply chain",
    "featurette2Heading1": "a trad : Un budget adapté",
    "featurette2Heading2": "a trad :  au modèle économique de nos clients",
    "featurette21SubHeading": "a trad : Un prix forfaitaire",
    "featurette21Content1": "a trad : Proportionnel à votre activité",
    "featurette21Content2": "a trad : 50 centimes d’euro par transaction",
    "featurette21Content3": "a trad : Sans abonnement ni engagement de durée",
    "featurette22SubHeading": "a trad : Modèle de prix basé du package standard, prêt à fonctionner",
    "featurette22Content1": "a trad : Mise à disposition d’un environnement sécurisé",
    "featurette22Content2": "a trad : Assistance à la configuration du logiciel",
    "featurette22Content3": "a trad : Formation en ligne",
    "featurette22Content4": "a trad : Interfaces standard",
    "featurette23SubHeading": "a trad : Le coût est facturé chaque mois, il est fonction du nombre :",
    "featurette23Content1": "a trad : De palettes réceptionnées et rangées",
    "featurette23Content2": "a trad : De prélèvements en stock pour expédition",
    "featurette23Content3": "a trad : De palettes en stock à chaque fin de mois",
    "featurette24SubHeading": "a trad : Services complémentaires en option",
    "featurette24Content1": "a trad : 800 euros par jour au delà des jours inclus dans le forfait",
    "featurette24Content2": "a trad : Formation complémentaire",
    "featurette24Content3": "a trad : Aide à la configuration ou au chargement des données",
    "featurette24Content4": "a trad : Personnalisation des interfaces standard",
    "featurette24Content5": "a trad : Assistance complémentaire personnalisée sur site",
    "featurette24Content6": "a trad : Activation de fonctions avancées",
    "featurette3Heading1": "a trad : La valeur ajouté de JustLogsIT",
    "featurette3Heading2": "a trad : S’intégrer au sein de Supply Chain et assurer une communication régulière et fiable de l’état des stocks et des travaux en cours avec les partenaires",
    "featurette31SubHeading": "a trad : JustLogsIT permet d’augmenter :",
    "featurette31Content1": "a trad : La vitesse et la fiabilité du système logistique",
    "featurette31Content2": "a trad : La fiabilité et la rotation du stock",
    "featurette31Content3": "a trad : La traçabilité et la visibilité du stock et des en-cours",
    "featurette31Content4": "a trad : L’engagement de service client",
    "featurette31Content5": "a trad : La ponctualité du départ des transports",
    "featurette31Content6": "a trad : La qualité de chaque opération",
    "featurette31Content7": "a trad : La planification des ressources humaines",
    "featurette31Content8": "a trad : Le pilotage des opérations et des ressources de sites qui ne peuvent pas se piloter à vue",
    "featurette31Content9": "a trad : La mesure de la performance",
    "featurette31Content10": "a trad : L’utilisation de l’espace et des équipements",
    "featurette31Content11": "a trad : La valeur ajoutée d’un stock qualitatif et productif, facteur de différentiation de la supply chain",
    "featurette32SubHeading": "a trad : JustLogsIT aide à réduire :",
    "featurette32Content1": "a trad : Les investissements en équipements",
    "featurette32Content2": "a trad : La place perdue en espace de stockage",
    "featurette32Content3": "a trad : La mauvaise utilisation des équipements et donc leur coût",
    "featurette32Content4": "a trad : Les pertes et la dépréciation de stock",
    "featurette32Content5": "a trad : Le stock de sécurité",
    "featurette32Content6": "a trad : Les coûts d’exploitation",
    "featurette32Content7": "a trad : Les heures supplémentaires",
    "featurette32Content8": "a trad : Le temps de recherche des produits dans le site",
    "featurette32Content9": "a trad : L’édition de papier",
    "featurette32Content10": "a trad : Les erreurs dues au facteur humain",
    "featurette32Content11": "a trad : Les livraisons express pour compenser les retards d’exécution",
    "featurette4Content1": "a trad : N'hésitez pas à nous ",
    "featurette4Content2": "a trad : contacter",
    "featurette4Content3": "a trad :  pour obtenir de plus amples informations ou demander une démo"
};

translations['fr']['home'] = {
    "carousel1Item1": "Logiciel de gestion logistique en ligne pour PME",
    "carousel2Item1": "Une solution adaptée aux besoins de PME industrielles, distributeurs et prestataires logistiques",
    "carousel2Item2": "Complète, elle dispose des fonctionnalités des leaders du marché, à un coût adapté",
    "carousel3Item1": "Simple et rapide à mettre en œuvre et à utiliser, aucune infrastructure informatique n’est à installer",
    "carousel3Item2": "Economique, le budget en coûts variables est lié au nombre de transactions",
    "carousel3Item3": "Connectée aux systèmes d’information des partenaires de vos supply chain",
    "marketingSeeDetails": "Voir détail",
    "marketingServicesHeading": "Services",
    "marketingServicesContent": "Mise en œuvre simple, fiable, économique et rapide de votre WMS",
    "marketingSolutionsHeading": "Solutions",
    "marketingSolutionsContent": "Supporte l’ensemble des processus des plates-formes logistiques",
    "marketingSupportHeading": "Support",
    "marketingSupportContent": "Bien utiliser votre solution sur site",
    "featurette1Heading1": "Une solution logicielle",
    "featurette1Heading2": " de gestion logistique en ligne",
    "featurette1Content1": "Adaptée aux besoins de PME industrielles, distributeurs et prestataires logistiques",
    "featurette1Content2": "Pour la gestion des magasins des sites de production, des plates formes de distribution, des entrepôts de stockage et des sites de préparation de commandes",
    "featurette1Content3": "Simple et rapide à mettre en œuvre et à utiliser, aucune infrastructure informatique n’est à installer",
    "featurette1Content4": "Complète, elle dispose des fonctionnalités des leaders du marché, à un coût adapté aux PME",
    "featurette1Content5": "Economique, le budget en coûts variables est lié au nombre de transactions, sans obligation d’abonnement ni d’engagement de durée",
    "featurette1Content6": "Fiable, sécurisée et toujours disponible pour les utilisateurs, dans le monde",
    "featurette1Content7": "Connectée aux systèmes d’information des partenaires de vos supply chain",
    "featurette2Heading1": "Un budget adapté",
    "featurette2Heading2": " au modèle économique de nos clients",
    "featurette21SubHeading": "Un prix forfaitaire",
    "featurette21Content1": "Proportionnel à votre activité",
    "featurette21Content2": "50 centimes d’euro par transaction",
    "featurette21Content3": "Sans abonnement ni engagement de durée",
    "featurette22SubHeading": "Modèle de prix basé du package standard, prêt à fonctionner",
    "featurette22Content1": "Mise à disposition d’un environnement sécurisé",
    "featurette22Content2": "Assistance à la configuration du logiciel",
    "featurette22Content3": "Formation en ligne",
    "featurette22Content4": "Interfaces standard",
    "featurette23SubHeading": "Le coût est facturé chaque mois, il est fonction du nombre :",
    "featurette23Content1": "De palettes réceptionnées et rangées",
    "featurette23Content2": "De prélèvements en stock pour expédition",
    "featurette23Content3": "De palettes en stock à chaque fin de mois",
    "featurette24SubHeading": "Services complémentaires en option",
    "featurette24Content1": "800 euros par jour au delà des jours inclus dans le forfait",
    "featurette24Content2": "Formation complémentaire",
    "featurette24Content3": "Aide à la configuration ou au chargement des données",
    "featurette24Content4": "Personnalisation des interfaces standard",
    "featurette24Content5": "Assistance complémentaire personnalisée sur site",
    "featurette24Content6": "Activation de fonctions avancées",
    "featurette3Heading1": "La valeur ajouté de JustLogsIT",
    "featurette3Heading2": "S’intégrer au sein de Supply Chain et assurer une communication régulière et fiable de l’état des stocks et des travaux en cours avec les partenaires",
    "featurette31SubHeading": "JustLogsIT permet d’augmenter :",
    "featurette31Content1": "La vitesse et la fiabilité du système logistique",
    "featurette31Content2": "La fiabilité et la rotation du stock",
    "featurette31Content3": "La traçabilité et la visibilité du stock et des en-cours",
    "featurette31Content4": "L’engagement de service client",
    "featurette31Content5": "La ponctualité du départ des transports",
    "featurette31Content6": "La qualité de chaque opération",
    "featurette31Content7": "La planification des ressources humaines",
    "featurette31Content8": "Le pilotage des opérations et des ressources de sites qui ne peuvent pas se piloter à vue",
    "featurette31Content9": "La mesure de la performance",
    "featurette31Content10": "L’utilisation de l’espace et des équipements",
    "featurette31Content11": "La valeur ajoutée d’un stock qualitatif et productif, facteur de différentiation de la supply chain",
    "featurette32SubHeading": "JustLogsIT aide à réduire :",
    "featurette32Content1": "Les investissements en équipements",
    "featurette32Content2": "La place perdue en espace de stockage",
    "featurette32Content3": "La mauvaise utilisation des équipements et donc leur coût",
    "featurette32Content4": "Les pertes et la dépréciation de stock",
    "featurette32Content5": "Le stock de sécurité",
    "featurette32Content6": "Les coûts d’exploitation",
    "featurette32Content7": "Les heures supplémentaires",
    "featurette32Content8": "Le temps de recherche des produits dans le site",
    "featurette32Content9": "L’édition de papier",
    "featurette32Content10": "Les erreurs dues au facteur humain",
    "featurette32Content11": "Les livraisons express pour compenser les retards d’exécution",
    "featurette4Content1": "N'hésitez pas à nous ",
    "featurette4Content2": "contacter",
    "featurette4Content3": " pour obtenir de plus amples informations ou demander une démo."

};