/**
 * Created by acouette on 05/06/16.
 */

translations['en']['solutions'] = {
    "mainHeader" : "Gestion de processus de plates-forme logistique",
    "mainItem1" : "Portefeuille des réceptions prévues",
    "mainItem2" : "Réception & Contrôle",
    "mainItem3" : "Optimisation de l’adressage des produits à ranger",
    "mainItem4" : "Identification",
    "mainItem5" : "Rangement en stock",
    "mainItem6" : "Optimisation du réapprovisionnement picking",
    "mainItem7" : "Gestion de stock",
    "mainItem8" : "Inventaire",
    "mainItem9" : "Représentation visuelle des zones de stockage",
    "mainItem10" : "Portefeuille des ordres",
    "mainItem11" : "Ordonnancement des opérations",
    "mainItem12" : "Optimisation des ordres de prélèvements",
    "mainItem13" : "Pilotage des ressources",
    "mainItem14" : "Prélèvement en stock",
    "mainItem15" : "Colisage",
    "mainItem16" : "Gestion des tournées de transport",
    "mainItem17" : "Exécution des chargements",
    "mainItem18" : "Edition des documents",
    "mainItem19" : "Expédition",
    "mainItem20" : "Traçabilité des flux logistiques, des numéros de lots",
    "mainItem21" : "Gestion des dates de péremption",
    "mainItem22" : "Les fichiers d’interfaces d’échange avec les autres solutions informatiques de l’entreprise ou des partenaires",
    "mainItem23" : "Tableaux de bord",
    "mainItem24" : "Echange des données avec les systèmes d’information de l’entreprise et des partenaires",
    "mainItem25" : "Transactions en support papier ou code à barre avec lecteur radio fréquence",
    "receptionHeader1" : "Le processus de ",
    "receptionHeader2" : "Réception",
    "reception1SubHeader": "Gestion des réceptions prévues en fonction de leur origine",
    "reception1Item1": "Interface, saisie, modification",
    "reception1Item2": "Produits finis en provenance des usines de production ou des fournisseurs",
    "reception1Item3": "Stock en cours de production ou composants pour réalisation de kit",
    "reception1Item4": "Transfert de stock en provenance d’un stock externe de débord",
    "reception1Item5": "Retour en provenance des clients et partenaires",
    "reception1Item6": "Approvisionnement de consommables destinés à couvrir les besoins opérationnels du site",
    "reception2SubHeader": "Réception et contrôle",
    "reception2Item1": "Imputation des entrées attendues, ou saisie des entrées ou scan des palettes réceptionnées",
    "reception2Item2": "Réception physique et identification",
    "reception2Item3": "Contrôle de conformité : colisage, article, lot, date, quantité, qualité...",
    "reception2Item4": "Modifications éventuelles et enregistrement dans le Système",
    "reception2Item5": "Gestion des statuts de contrôle qualité",
    "reception3SubHeader": "Optimisation de l’adressage des produits à ranger en stock",
    "reception3Item1": "Algorithme de recherche d’adresse optimum en fonction de critères combinés et hiérarchisés : article, contenants, volume, magasin, classes de rotation et de la nature des produits",
    "reception3Item2": "Ou adressage manuel déclaratif par l’opérateur",
    "reception4SubHeader": "Etiquetage",
    "reception4Item1": "Identification de la palette, adresse de rangement en clair et en code à barre",
    "reception4Item2": "Interface",
    "stockHeader1" : "Les opérations de gestion du ",
    "stockHeader2" : "Stock",
    "stock1SubHeader": "Rangement en stock",
    "stock1Item1": "Etiquette, liste de rangement, lecteur mobile code à barre",
    "stock1Item2": "Validation du rangement du bon emplacement et de la disponibilité du stock",
    "stock2SubHeader": "Optimisation du réapprovisionnement picking",
    "stock2Item1": "Déclenchement des besoins du réapprovisionnement des picking en fonction d’un seuil paramétrable",
    "stock2Item2": "Edition des missions par liste, étiquette ou affectation de mission sur terminal mobile",
    "stock3SubHeader": "Gestion de stock",
    "stock3Item1": "Consultation Etat du stock aux emplacements par article, lot, date et statuts (libre, en cours de contrôle, bloqué, réservé…)",
    "stock3Item2": "Historique des mouvements de stock par nature, article, lot, emplacement",
    "stock3Item3": "Gestion des écarts et interfaces",
    "stock4SubHeader": "Inventaire",
    "stock4Item1": "Procédure d’inventaire",
    "stock4Item2": "Interfaces",
    "stock5SubHeader": "Représentation visuelle des zones de stockage",
    "stock5Item1": "En indiquant leur statut : libre, occupé, encours",
    "pickupHeader1" : "Prélévements de produits",
    "pickupHeader2" : " en stock",
    "pickup1SubHeader": "Gestion du portefeuille des ordres de livraison",
    "pickup2SubHeader": "Ordonnancement des opérations",
    "pickup2Item1": "Les principaux critères de d’ordonnancement des missions de picking sont : date de livraison, type d‘ordre de livraison, client, transporteur, mode de transport ou tournée de transport (si ellse sont connues)",
    "pickup3SubHeader": "Optimisation des ordres de prélèvements",
    "pickup3Item1": "Edition de listes de prélévement ou envois de missions vers des terminaux mobiles lecteurs de CAB",
    "pickup3Item2": "Les critères d’optimisation du parcours des préparateurs de commandes sont : cheminement dans les allées, rangées et niveaux, séparation ou regroupement entre zones de prélèvement , séparation ou regroupement réserve/picking, multi ordres de Livraison , multi client ou non",
    "pickup4SubHeader": "Optimisation des ressources de préparation des commandes",
    "pickup4Item1": "Les éléments de pilotage sont la répartition de charges des missions vers les différents terminaux mobiles, l’optimisation du déclenchement des réapprovisionnements préventifs des pickings",
    "pickup5SubHeader": "Prélèvement en stock",
    "pickup5Item1": "Validation de l’emplacement et de la quantité",
    "pickup6SubHeader": "Colisage",
    "pickup6Item1": "Type de colis, numéro, poids, dimensions",
    "pickup6Item2": "Etiquette d’expédition : quai d’expédition, adresse livraison, transporteur",

};



translations['fr']['solutions'] = {

    "mainHeader" : "Gestion de processus de plates-forme logistique",
    "mainItem1" : "Portefeuille des réceptions prévues",
    "mainItem2" : "Réception & Contrôle",
    "mainItem3" : "Optimisation de l’adressage des produits à ranger",
    "mainItem4" : "Identification",
    "mainItem5" : "Rangement en stock",
    "mainItem6" : "Optimisation du réapprovisionnement picking",
    "mainItem7" : "Gestion de stock",
    "mainItem8" : "Inventaire",
    "mainItem9" : "Représentation visuelle des zones de stockage",
    "mainItem10" : "Portefeuille des ordres",
    "mainItem11" : "Ordonnancement des opérations",
    "mainItem12" : "Optimisation des ordres de prélèvements",
    "mainItem13" : "Pilotage des ressources",
    "mainItem14" : "Prélèvement en stock",
    "mainItem15" : "Colisage",
    "mainItem16" : "Gestion des tournées de transport",
    "mainItem17" : "Exécution des chargements",
    "mainItem18" : "Edition des documents",
    "mainItem19" : "Expédition",
    "mainItem20" : "Traçabilité des flux logistiques, des numéros de lots",
    "mainItem21" : "Gestion des dates de péremption",
    "mainItem22" : "Les fichiers d’interfaces d’échange avec les autres solutions informatiques de l’entreprise ou des partenaires",
    "mainItem23" : "Tableaux de bord",
    "mainItem24" : "Echange des données avec les systèmes d’information de l’entreprise et des partenaires",
    "mainItem25" : "Transactions en support papier ou code à barre avec lecteur radio fréquence",
    "receptionHeader1" : "Le processus de ",
    "receptionHeader2" : "Réception",
    "reception1SubHeader": "Gestion des réceptions prévues en fonction de leur origine",
    "reception1Item1": "Interface, saisie, modification",
    "reception1Item2": "Produits finis en provenance des usines de production ou des fournisseurs",
    "reception1Item3": "Stock en cours de production ou composants pour réalisation de kit",
    "reception1Item4": "Transfert de stock en provenance d’un stock externe de débord",
    "reception1Item5": "Retour en provenance des clients et partenaires",
    "reception1Item6": "Approvisionnement de consommables destinés à couvrir les besoins opérationnels du site",
    "reception2SubHeader": "Réception et contrôle",
    "reception2Item1": "Imputation des entrées attendues, ou saisie des entrées ou scan des palettes réceptionnées",
    "reception2Item2": "Réception physique et identification",
    "reception2Item3": "Contrôle de conformité : colisage, article, lot, date, quantité, qualité...",
    "reception2Item4": "Modifications éventuelles et enregistrement dans le Système",
    "reception2Item5": "Gestion des statuts de contrôle qualité",
    "reception3SubHeader": "Optimisation de l’adressage des produits à ranger en stock",
    "reception3Item1": "Algorithme de recherche d’adresse optimum en fonction de critères combinés et hiérarchisés : article, contenants, volume, magasin, classes de rotation et de la nature des produits",
    "reception3Item2": "Ou adressage manuel déclaratif par l’opérateur",
    "reception4SubHeader": "Etiquetage",
    "reception4Item1": "Identification de la palette, adresse de rangement en clair et en code à barre",
    "reception4Item2": "Interface",
    "stockHeader1" : "Les opérations de gestion du ",
    "stockHeader2" : "Stock",
    "stock1SubHeader": "Rangement en stock",
    "stock1Item1": "Etiquette, liste de rangement, lecteur mobile code à barre",
    "stock1Item2": "Validation du rangement du bon emplacement et de la disponibilité du stock",
    "stock2SubHeader": "Optimisation du réapprovisionnement picking",
    "stock2Item1": "Déclenchement des besoins du réapprovisionnement des picking en fonction d’un seuil paramétrable",
    "stock2Item2": "Edition des missions par liste, étiquette ou affectation de mission sur terminal mobile",
    "stock3SubHeader": "Gestion de stock",
    "stock3Item1": "Consultation Etat du stock aux emplacements par article, lot, date et statuts (libre, en cours de contrôle, bloqué, réservé…)",
    "stock3Item2": "Historique des mouvements de stock par nature, article, lot, emplacement",
    "stock3Item3": "Gestion des écarts et interfaces",
    "stock4SubHeader": "Inventaire",
    "stock4Item1": "Procédure d’inventaire",
    "stock4Item2": "Interfaces",
    "stock5SubHeader": "Représentation visuelle des zones de stockage",
    "stock5Item1": "En indiquant leur statut : libre, occupé, encours",
    "pickupHeader1" : "Prélévements de produits",
    "pickupHeader2" : " en stock",
    "pickup1SubHeader": "Gestion du portefeuille des ordres de livraison",
    "pickup2SubHeader": "Ordonnancement des opérations",
    "pickup2Item1": "Les principaux critères de d’ordonnancement des missions de picking sont : date de livraison, type d‘ordre de livraison, client, transporteur, mode de transport ou tournée de transport (si ellse sont connues)",
    "pickup3SubHeader": "Optimisation des ordres de prélèvements",
    "pickup3Item1": "Edition de listes de prélévement ou envois de missions vers des terminaux mobiles lecteurs de CAB",
    "pickup3Item2": "Les critères d’optimisation du parcours des préparateurs de commandes sont : cheminement dans les allées, rangées et niveaux, séparation ou regroupement entre zones de prélèvement , séparation ou regroupement réserve/picking, multi ordres de Livraison , multi client ou non",
    "pickup4SubHeader": "Optimisation des ressources de préparation des commandes",
    "pickup4Item1": "Les éléments de pilotage sont la répartition de charges des missions vers les différents terminaux mobiles, l’optimisation du déclenchement des réapprovisionnements préventifs des pickings",
    "pickup5SubHeader": "Prélèvement en stock",
    "pickup5Item1": "Validation de l’emplacement et de la quantité",
    "pickup6SubHeader": "Colisage",
    "pickup6Item1": "Type de colis, numéro, poids, dimensions",
    "pickup6Item2": "Etiquette d’expédition : quai d’expédition, adresse livraison, transporteur",
};